<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-07-07T18:42:50Z" name="Default suite" finished-at="2023-07-07T18:43:31Z" duration-ms="40940">
    <groups>
    </groups>
    <test started-at="2023-07-07T18:42:50Z" name="Default test" finished-at="2023-07-07T18:43:31Z" duration-ms="40940">
      <class name="day1.basic_testng.Actitime4">
        <test-method signature="a_loginActitime()[pri:0, instance:day1.basic_testng.Actitime4@5386659f]" started-at="2023-07-08T00:12:50Z" name="a_loginActitime" finished-at="2023-07-08T00:13:17Z" duration-ms="27069" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- a_loginActitime -->
        <test-method signature="b_verifyTaskcreation()[pri:0, instance:day1.basic_testng.Actitime4@5386659f]" started-at="2023-07-08T00:13:17Z" name="b_verifyTaskcreation" finished-at="2023-07-08T00:13:29Z" duration-ms="11909" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[task is not created expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: task is not created expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at day1.basic_testng.Actitime4.b_verifyTaskcreation(Actitime4.java:103)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- b_verifyTaskcreation -->
        <test-method signature="c_verifyTaskDeletion()[pri:0, instance:day1.basic_testng.Actitime4@5386659f]" started-at="2023-07-08T00:13:29Z" name="c_verifyTaskDeletion" finished-at="2023-07-08T00:13:31Z" duration-ms="1934" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- c_verifyTaskDeletion -->
      </class> <!-- day1.basic_testng.Actitime4 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
